version: '3.4'

services:
  dvmn_bot:
    image: dvmn_bot:prod
    build:
      context: .
      target: prod
    container_name: dvmn_bot
    restart: "always"
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
