version: '3.4'

services:
  dvmn_bot:
    extends:
      # Снимите комментарий с нужного compose-файла
      #file: compose-develop.yml
      file: compose-prod.yml
      service: dvmn_bot

networks:
  default:
    name: webapp_backend
    external: true

