version: '3.4'

services:
  dvmn_bot:
    image: dvmn_bot:develop
    build:
      context: .
      target: develop
    container_name: dvmn_bot
    command: [ "python", "./bot.py" ]
    restart: "always"
    volumes:
      - ./:/usr/src/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

